USE MONGODB;
SELECT * FROM STUDENTS;

SELECT STUDENTS.ID, STUDENTS.NAME, STUDENTS.CITY,
ATTENDANCE.PERCENTAGE,
MARKS.JAVA, MARKS.PYTHON,
(MARKS.JAVA+MARKS.PYTHON) AS TOTAL,
(MARKS.JAVA+MARKS.PYTHON)/2 AS AVERAGE,
RANK() OVER ( ORDER BY ( MARKS.JAVA+MARKS.PYTHON ) DESC ) AS POSITION
FROM STUDENTS left JOIN ATTENDANCE ON STUDENTS.ID=ATTENDANCE.ID 
left JOIN MARKS ON STUDENTS.ID=MARKS.ID;

SELECT 
    S.ID, 
    S.NAME, 
    S.CITY,
    A.PERCENTAGE,
    M.JAVA, 
    M.PYTHON,
    (M.JAVA + M.PYTHON) AS TOTAL,
    (M.JAVA + M.PYTHON) / 2 AS AVERAGE,
    RANK() OVER (ORDER BY (M.JAVA + M.PYTHON) DESC) AS POSITION,
    C.AVG_JAVA,
    C.AVG_PYTHON,
    C.CLASS_AVERAGE
FROM STUDENTS S
JOIN ATTENDANCE A ON S.ID = A.ID
JOIN MARKS M ON S.ID = M.ID
CROSS JOIN (
    SELECT 
        AVG(JAVA)   AS AVG_JAVA,
        AVG(PYTHON) AS AVG_PYTHON,
        AVG((JAVA + PYTHON)/2) AS CLASS_AVERAGE
    FROM MARKS
) C;
