use babu;

SELECT 
EMP.ID,EMP.NAME,EMP.DESIGN,EMP.DOJ,
SALARY.SDATE,
SALARY.AMT 
FROM EMP LEFT JOIN SALARY
ON EMP.ID = SALARY.ID;

SELECT 
STUDENTS.NAME, STUDENTS.GENDER, 
ATTENDANCE.ADATE, ATTENDANCE.ASTATUS
FROM STUDENTS INNER JOIN ATTENDANCE
ON STUDENTS.ID = ATTENDANCE.ID;