CREATE TABLE STUDENTS (
ID NUMBER(5) NOT NULL PRIMARY KEY,
NAME VARCHAR(20),
CITY VARCHAR(20),
AGE  NUMBER(5));

INSERT INTO STUDENTS VALUES (101, 'Babu', 'Chennai',21);
INSERT INTO STUDENTS VALUES (102, 'Bala', 'Chennai',16);
INSERT INTO STUDENTS VALUES (103, 'Arun', 'Maraimalai nagar',22);
INSERT INTO STUDENTS VALUES (104, 'Dharaga', 'Kudikkadu',2);

-- MIN()
SELECT ID, NAME, CITY, AGE FROM STUDENTS WHERE AGE = (SELECT MIN(AGE) FROM STUDENTS);

-- MAX()
SELECT * FROM STUDENTS WHERE AGE = (SELECT MAX(AGE) FROM STUDENTS);

-- AVG()
SELECT AVG(AGE) AS AVERAGE_AGE FROM STUDENTS;

-- LENGTH()
SELECT * FROM STUDENTS WHERE LENGTH(CITY)  = (SELECT MAX(LENGTH(CITY)) FROM STUDENTS);

-- COUNT()
SELECT CITY, COUNT(CITY) FROM STUDENTS GROUP BY CITY;

-- SUM()
SELECT SUM(AGE) FROM STUDENTS;