CREATE TABLE STUDENTS (
ID INT NOT NULL PRIMARY KEY, -- NUMBER(5)
NAME VARCHAR(20),  -- VARCHAR2(50)
CITY VARCHAR(20));

ALTER TABLE STUDENTS ADD AGE INT;

TRUNCATE TABLE STUDENTS;

RENAME TABLE STUDENTS TO CSTSTUDENTS; -- RENAME STUDENTS TO CSTSTUDENTS; (ORACLE)

DROP TABLE CSTSTUDENTS;