CREATE TABLE STUDENTS (
ID INT PRIMARY KEY NOT NULL,
NAME VARCHAR(20),
CITY VARCHAR(20));

INSERT INTO STUDENTS VALUES (101,'Babu','Chennai'); 	-- INSERT
INSERT INTO STUDENTS VALUES (102,'Bala','Chennai');

UPDATE STUDENTS SET NAME = 'Ganeshbabu' WHERE ID = 101; -- UPDATE

DELETE FROM STUDENTS WHERE ID = 102;	-- DELETE

SELECT * FROM STUDENTS;		-- SELECT