SET AUTOCOMMIT = 0;
CREATE TABLE STUDENTS (
ID INT NOT NULL PRIMARY KEY,
NAME VARCHAR(20),
CITY VARCHAR(20));

INSERT INTO STUDENTS VALUES (101, 'Babu', 'Chennai');
INSERT INTO STUDENTS VALUES (102, 'BALA', 'Chennai');
SAVEPOINT A;

INSERT INTO STUDENTS VALUES (103, 'Arun', 'Maraimalai Nagar');
SAVEPOINT B;

INSERT INTO STUDENTS VALUES (104, 'BALA', 'Kudikkadu');
SELECT * FROM STUDENTS;

ROLLBACK TO SAVEPOINT B;
SELECT * FROM STUDENTS;

ROLLBACK TO SAVEPOINT A;
SELECT * FROM STUDENTS;

COMMIT;
ROLLBACK;
SELECT * FROM STUDENTS;