CREATE TABLE ORDERS(
ORDER_ID INT NOT NULL PRIMARY KEY,
ITEM VARCHAR(50)
);

INSERT INTO ORDERS VALUES 
(1,101,"Coffee"),
(2,102,"Tea"),
(3,103,"Marie gold"),
(4,104,"Good day"),
(5,105,"Milk bikis"),
(6,106,"5 star");

SELECT * FROM USERS;

SELECT 
USERS.ID, USERS.NAME, ORDERS.ORDER_ID,ORDERS.ITEM 
FROM USERS 
JOIN ORDERS ON 
USERS.ID = ORDERS.ORDER_ID;

ALTER TABLE ORDERS ADD COLUMN ID INT NOT NULL;

SELECT * FROM ORDERS;

ALTER TABLE ORDERS 
MODIFY COLUMN ID INT NOT NULL FIRST;

truncate orders;

CREATE TABLE DELIVERY(
ID INT PRIMARY KEY NOT NULL,
STATUS VARCHAR(10));

INSERT INTO DELIVERY VALUES
(1,"Served"),
(2,"Served"),
(3,"pending"),
(4,"Served"),
(5,"pending"),
(6,"Served");

use ganesh;

SELECT ORDERS.ORDER_ID, USERS.NAME, ORDERS.ITEM, DELIVERY.STATUS 
FROM USERS JOIN ORDERS 
ON USERS.ID = ORDERS.ID
JOIN DELIVERY 
ON USERS.ID = DELIVERY.ID;