CREATE DATABASE MONGODB;
USE MONGODB;
CREATE TABLE STUDENTS(
ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(50),
CITY VARCHAR(50)
);
INSERT INTO STUDENTS (ID,NAME,CITY)
VALUES
(101,"Babu","Madhuranthagam"),
(102,"Dilli","Manamathy"),
(103,"vikki","Kanchipuram");
SELECT * FROM STUDENTS;

CREATE TABLE ATTENDANCE(
ID INT NOT NULL PRIMARY KEY,
PERCENTAGE INT
);
INSERT INTO ATTENDANCE (ID, PERCENTAGE)
VALUES
(101,95),
(102,89),
(103,87);
SELECT * FROM ATTENDANCE;

SELECT STUDENTS.ID, STUDENTS.NAME, STUDENTS.CITY, ATTENDANCE.PERCENTAGE FROM STUDENTS JOIN ATTENDANCE ON STUDENTS.ID = ATTENDANCE.ID;
commit;

