SELECT ID, NAME, AGE FROM STUDENTS WHERE AGE=(SELECT MIN(AGE) FROM STUDENTS); -- MIN()

SELECT MAX(AGE) FROM STUDENTS; -- MAX()

SELECT ID, NAME, AGE FROM STUDENTS WHERE AGE > 20;
SELECT COUNT(*) FROM STUDENTS WHERE AGE > 20; -- COUNT(*)

SELECT AVG(AGE) FROM STUDENTS; -- AVG()

SELECT CITY AS MAX_CITY_LENGTH, LENGTH(city) AS LENGTH
FROM STUDENTS  
WHERE LENGTH(CITY) = (SELECT MAX(LENGTH(city)) FROM STUDENTS); -- MAX() + LENGTH()

SELECT SUM(AGE) FROM STUDENTS; -- SUM()

SELECT 
GROUP_CONCAT(name ORDER BY name SEPARATOR ', ') AS ALLNAMES, 
GROUP_CONCAT(CITY ORDER BY CITY SEPARATOR ', ') AS ALLCITY
FROM STUDENTS;

-- SELECT LISTAGG(name, ', ') WITHIN GROUP (ORDER BY name) AS all_names
-- FROM STUDENTS; ORACLE

SELECT * FROM STUDENTS ORDER BY AGE;

use babu;