CREATE TABLE STUDENTS (
ID INT PRIMARY KEY NOT NULL,
NAME VARCHAR(50), 	-- VARCHAR2(50)
CITY VARCHAR(20));  -- VARCHAR2(20)

ALTER TABLE STUDENTS ADD AGE INT(3); -- NUMBER(3)

TRUNCATE TABLE STUDENTS;

RENAME TABLE STUDENTS TO CSTSTUDENTS;

DROP TABLE CSTSTUDENTS;