CREATE TABLE CSTATTENDANCE (
ID INT PRIMARY KEY NOT NULL,
PERCENTAGE INT );

INSERT INTO CSTATTENDANCE VALUES (101, 96);
INSERT INTO CSTATTENDANCE VALUES (102, 92);
INSERT INTO CSTATTENDANCE VALUES (103, 89);
INSERT INTO CSTATTENDANCE VALUES (104, 78);

SELECT * FROM CSTATTENDANCE;

SELECT 
STUDENTS.ID, STUDENTS.NAME, STUDENTS.AGE, STUDENTS.CITY,
CSTATTENDANCE.PERCENTAGE
FROM STUDENTS JOIN CSTATTENDANCE 
ON STUDENTS.ID = CSTATTENDANCE.ID;
